# Usando Python 3.14
FROM python:3.14-slim

# Diretório de trabalho no container
WORKDIR /app

# Copiar requisitos
COPY requirements.txt .

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código do backend
COPY . .

# Comando default (vai rodar producer_users, pode mudar depois)
CMD ["python", "-m", "app.producer.producer_users"]
